### PR TITLE
Edit URLs for project rename

### PR DESCRIPTION
**Pull request by stnly**

### CODE REVIEW

**Comment by fhunleth** [comment]
Thanks!

**Comment by stnly** [comment]
The sha256 hashes needs to be changed too.

**Comment by fhunleth** [comment]
Oops! We'll have to get @kfatehi in on this then. The builds from the master branch change on every commit, so this won't work for long even if we fix the sha256 hashes.

**Comment by kfatehi** [comment]
right, temporarily they can be changed to empty string or commented out

**Pull request merged**
